<?

$settings_map = Array( OCI_BRIDGEID       => Array(SPECTEL_BRIDGEID   => Array('securitytype'       => Array( null => 1, 
													      0    => 1,
													      1    => 2,
													      2    => 2,
													      3    => 2 ), 
									       'startmode'          => Array( null => 0,
													      0    => 0,
													      1    => 1,
													      2    => 1,
													      3    => 1,
													      4    => 1 ), 
									       'entryannouncement'  => Array( null => 0, 
													      0    => 0, 
													      1    => 2, 
													      2    => 1, 
													      3    => 3 ),
									       'exitannouncement'   => Array( null => 0, 
													      0    => 0, 
													      1    => 2, 
													      2    => 1, 
													      3    => 3 ),
									       'namerecording'      => Array( null => 1, 
													      0    => 1, 
													      1    => 3 ), 
									       'recordingsignal'    => Array( null => 0, 
													      0    => 0, 
													      2    => 2 ), 
									       'dialout'            => Array( null => 0, 
													      0    => 0, 
													      1    => 1 ),
									       'endonchairhangup'   => Array( null => 0, 
													      0    => 0,
													      1    => 1 ),
									       'endingsignal'       => Array( null => null ),
									       'dtmfsignal'         => Array( null => null ),
									       'digitentry1'        => Array( null => null ),
									       'confirmdigitentry1' => Array( null => null ),
									       'digitentry2'        => Array( null => null ),
									       'confirmdigitentry2' => Array( null => null )), 

						   INTERCALL_BRIDGEID => Array('securitytype'       => Array( null => null ), 
									       'startmode'          => Array( null => 0, 
													      0    => 0, 
													      1    => 1, 
													      2    => 1, 
													      3    => 1, 
													      4    => 1 ), 
									       'entryannouncement'  => Array( null => 0, 
													      0    => 0, 
													      1    => 1, 
													      2    => 1, 
													      3    => 2,
													      4    => 1 ),
									       'exitannouncement'   => Array( null => 0, 
													      0    => 0, 
													      1    => 1, 
													      2    => 1, 
													      3    => 2,
													      4    => 1),
									       'namerecording'      => Array( null => 0, 
													      0    => 0, 
													      1    => 1 ), 
									       'dialout'            => Array( null => 0, 
													      0    => 0, 
													      1    => 1 ),
									       'endonchairhangup'   => Array( null => 0, 
													      0    => 0,
													      1    => 1 ),
									       'recordingsignal'    => Array( null => null ), 
									       'endingsignal'       => Array( null => null ),
									       'dtmfsignal'         => Array( null => null ),
									       'digitentry1'        => Array( null => null ),
									       'confirmdigitentry1' => Array( null => null ),
									       'digitentry2'        => Array( null => null ),
									       'confirmdigitentry2' => Array( null => null )), 

						   BT_BRIDGEID => Array( 'securitytype'       => Array( null => null ), 
									 'startmode'          => Array( null => 0, 
													0    => 0, 
													1    => 1, 
													2    => 2), 
									 'entryannouncement'  => Array( null => 0, 
													0    => 0, 
													1    => 1, 
													2    => 1,
													3    => 2,
													4    => 2),
									 'exitannouncement'   => Array( null => 0, 
													0    => 0, 
													1    => 1, 
													2    => 1, 
													3    => 2, 
													4    => 2),
									 'namerecording'      => Array( null => 0, 
													0    => 0, 
													1    => 1 ),
									 'dialout'            => Array( null => 0, 
													0    => 0, 
													1    => 1 ),
									 'endonchairhangup'   => Array( null => 0, 
													0    => 0,
													1    => 1 ),
									 'recordingsignal'    => Array( null => null ), 
									 'endingsignal'       => Array( null => null ),
									 'dtmfsignal'         => Array( null => null ),
									 'digitentry1'        => Array( null => null ),
									 'confirmdigitentry1' => Array( null => null ),
									 'digitentry2'        => Array( null => null ),
									 'confirmdigitentry2' => Array( null => null ))), 
			   
		       SPECTEL_BRIDGEID   => Array(OCI_BRIDGEID       => Array('securitytype'       => Array( null => 0, 
													      1    => 0, 
													      2    => 2 ),
									       'startmode'          => Array( null => 0, 
													      0    => 0, 
													      1    => 1 ), 
									       'entryannouncement'  => Array( null => 0, 
													      0    => 0, 
													      1    => 2, 
													      2    => 1, 
													      3    => 3, 
													      4    => 2 ),
									       'exitannouncement'   => Array( null => 0, 
													      0    => 0, 
													      1    => 2, 
													      2    => 1, 
													      3    => 3, 
													      4    => 2 ),
									       'namerecording'      => Array( null => 0, 
													      1    => 0, 
													      2    => 1, 
													      3    => 1, 
													      4    => 1 ), 
									       'recordingsignal'    => Array( null => 0, 
													      0    => 0, 
													      1    => 2,
													      2    => 2 ),
									       'dialout'            => Array( null => 0, 
													      0    => 0, 
													      1    => 1 ),
									       'endonchairhangup'   => Array( null => 0, 
													      0    => 0,
													      1    => 1 ), 
									       'endingsignal'       => Array( null => 0 ),
									       'dtmfsignal'         => Array( null => 0 ),
									       'digitentry1'        => Array( null => 0 ),
									       'confirmdigitentry1' => Array( null => 0 ),
									       'digitentry2'        => Array( null => 0 ),
									       'confirmdigitentry2' => Array( null => 0 )),

						   INTERCALL_BRIDGEID => Array('securitytype'       => Array( null => null ), 
									       'startmode'          => Array( null => 0, 
													      0    => 0, 
													      1    => 1 ), 
									       'entryannouncement'  => Array( null => 0, 
													      0    => 0, 
													      1    => 1, 
													      2    => 1, 
													      3    => 2, 
													      4    => 1 ),
									       'exitannouncement'   => Array( null => 0, 
													      0    => 0, 
													      1    => 1, 
													      2    => 1, 
													      3    => 2, 
													      4    => 1 ),
									       'namerecording'      => Array( null => 0, 
													      1    => 0, 
													      2    => 1, 
													      3    => 1, 
													      4    => 1 ),
									       'dialout'            => Array( null => 0, 
													      0    => 0, 
													      1    => 1 ),
									       'endonchairhangup'   => Array( null => 0, 
													      0    => 0,
													      1    => 1 ), 
									       'recordingsignal'    => Array( null => null ), 
									       'endingsignal'       => Array( null => null ),
									       'dtmfsignal'         => Array( null => null ),
									       'digitentry1'        => Array( null => null ),
									       'confirmdigitentry1' => Array( null => null ),
									       'digitentry2'        => Array( null => null ),
									       'confirmdigitentry2' => Array( null => null )),
						   BT_BRIDGEID => Array( 'securitytype'       => Array( null => null ), 
									 'startmode'          => Array( null => 0, 
													0    => 0, 
													1    => 1), 
									 'entryannouncement'  => Array( null => 0, 
													0    => 0, 
													1    => 1,
													2    => 1, 
													3    => 2, 
													4    => 2),
									 'exitannouncement'   => Array( null => 0, 
													0    => 0, 
													1    => 1, 
													2    => 1, 
													3    => 2,
													4    => 2),
									 'namerecording'      => Array( null => 0, 
													1    => 0, 
													3    => 1 ), 
									 'dialout'            => Array( null => 0, 
													0    => 0, 
													1    => 1 ),
									 'endonchairhangup'   => Array( null => 0, 
													0    => 0,
													1    => 1 ),
									 'recordingsignal'    => Array( null => null ), 
									 'endingsignal'       => Array( null => null ),
									 'dtmfsignal'         => Array( null => null ),
									 'digitentry1'        => Array( null => null ),
									 'confirmdigitentry1' => Array( null => null ),
									 'digitentry2'        => Array( null => null ),
									 'confirmdigitentry2' => Array( null => null ))),			   
		       INTERCALL_BRIDGEID => Array(OCI_BRIDGEID       => Array('securitytype'       => Array( null => 0 ), 
									       'startmode'          => Array( null => 0, 
													      0    => 0, 
													      1    => 1 ), 
									       'entryannouncement'  => Array( null => 0, 
													      0    => 0, 
													      1    => 0, 
													      2    => 3, 
													      3    => 2 ),
									       'exitannouncement'   => Array( null => 0, 
													      0    => 0, 
													      1    => 0, 
													      2    => 3, 
													      3    => 2 ),
									       'namerecording'      => Array( null => 0, 
													      0    => 0, 
													      1    => 1 ),
									       'dialout'            => Array( null => 0, 
													      0    => 0, 
													      1    => 1 ),
									       'endonchairhangup'   => Array( null => 0, 
													      0    => 0,
													      1    => 1 ), 
									       'recordingsignal'    => Array( null => 0 ), 
									       'endingsignal'       => Array( null => 0 ),
									       'dtmfsignal'         => Array( null => 0 ),
									       'digitentry1'        => Array( null => 0 ),
									       'confirmdigitentry1' => Array( null => 0 ),
									       'digitentry2'        => Array( null => 0 ),
									       'confirmdigitentry2' => Array( null => 0 )),

						   SPECTEL_BRIDGEID   => Array('securitytype'       => Array( null => 1 ), 
									       'startmode'          => Array( null => 0, 
													      0    => 0, 
													      1    => 1 ), 
									       'entryannouncement'  => Array( null => 0, 
													      0    => 0, 
													      1    => 2, 
													      2    => 3, 
													      3    => 4 ),
									       'exitannouncement'   => Array( null => 0, 
													      0    => 0, 
													      1    => 2, 
													      2    => 3, 
													      3    => 4 ),
									       'namerecording'      => Array( null => 1, 
													      0    => 1, 
													      1    => 3 ), 
									       'recordingsignal'    => Array( null => 0 ),
									       'dialout'            => Array( null => 0, 
													      0    => 0, 
													      1    => 1 ),
									       'endonchairhangup'   => Array( null => 0, 
													      0    => 0,
													      1    => 1 ), 
									       'endingsignal'       => Array( null => null ),
									       'dtmfsignal'         => Array( null => null ),
									       'digitentry1'        => Array( null => null ),
									       'confirmdigitentry1' => Array( null => null ),
									       'digitentry2'        => Array( null => null ),
									       'confirmdigitentry2' => Array( null => null )), 
						   BT_BRIDGEID => Array( 'securitytype'       => Array( null => null ), 
									 'startmode'          => Array( null => 0, 
													0    => 0, 
													1    => 1), 
									 'entryannouncement'  => Array( null => 0, 
													0    => 0, 
													1    => 1,
													2    => 2, 
													3    => 2),
									 'exitannouncement'   => Array( null => 0, 
													0    => 0, 
													1    => 1, 
													2    => 2, 
													3    => 2),
									 'namerecording'      => Array( null => 0, 
													0    => 0, 
													1    => 1 ), 
									 'dialout'            => Array( null => 0, 
													0    => 0, 
													1    => 1 ),
									 'endonchairhangup'   => Array( null => 0, 
													0    => 0,
													1    => 1 ),
									 'recordingsignal'    => Array( null => null ), 
									 'endingsignal'       => Array( null => null ),
									 'dtmfsignal'         => Array( null => null ),
									 'digitentry1'        => Array( null => null ),
									 'confirmdigitentry1' => Array( null => null ),
									 'digitentry2'        => Array( null => null ),
									 'confirmdigitentry2' => Array( null => null ))), 
		       BT_BRIDGEID => Array(OCI_BRIDGEID       => Array('startmode'         => Array( null => 0,
												      0    => 0, 
												      1    => 1, 
												      2    => 2 ), 
									'entryannouncement' => Array( null => 0, 
												      0    => 0, 
												      1    => 1, 
												      2    => 3 ),
									'exitannouncement'  => Array( null => 0, 
												      0    => 0, 
												      1    => 1, 
												      2    => 3 ), 
									'namerecording'     => Array( null => 0, 
												      0    => 0, 
												      1    => 1 ),
									'dialout'            => Array( null => 0, 
												       0    => 0, 
												       1    => 1 ),
									'endonchairhangup'   => Array( null => 0, 
												       0    => 0,
												       1    => 1 ),
									'digitentry1'         => Array( null => 0, 
													0    => 0, 
													1    => 1 )), 
					    SPECTEL_BRIDGEID   => Array('startmode'         => Array( null => 0, 
												      0    => 0,
												      1    => 1 ), 
									'entryannouncement' => Array( null => 0, 
												      0    => 0, 
												      1    => 1, 
												      3    => 2 ),
									'exitannouncement'  => Array( null => 0, 
												      0    => 0, 
												      1    => 1, 
												      3    => 2 ), 
									'namerecording'     => Array( null => 1, 
												      1    => 0, 
												      3    => 1 ),
									'dialout'            => Array( null => 0, 
												       0    => 0, 
												       1    => 1 ),
									'endonchairhangup'   => Array( null => 0, 
												       0    => 0,
												       1    => 1 ),
									'digitentry1'         => Array( null => 0, 
													0    => 0, 
													1    => 1 )), 
					    INTERCALL_BRIDGEID => Array('startmode'         => Array( null => 0, 
												      0    => 0, 
												      1    => 1), 
									'entryannouncement' => Array( null => 0, 
												      0    => 0, 
												      1    => 1, 
												      2    => 2),
									'exitannouncement'  => Array( null => 0, 
												      0    => 0, 
												      1    => 1, 
												      2    => 2 ), 
									'namerecording'     => Array(null => 0, 
												      0    => 0, 
												      1    => 1),
									'dialout'            => Array( null => 0, 
												       0    => 0, 
												       1    => 1 ),
									'endonchairhangup'   => Array( null => 0, 
												       0    => 0,
												       1    => 1 ),
									'digitentry1'         => Array( null => 0, 
													0    => 0, 
													1    => 1 ))));